/**
 * Predefined attack scenarios for the Attack Simulator module.
 * Each scenario defines metadata, compatible targets, and log templates.
 */

export const ATTACK_SCENARIOS = [
  {
    id: 'sql-injection',
    name: 'SQL Injection',
    icon: '💉',
    category: 'Web Attack',
    color: 'text-amber-400',
    border: 'border-amber-400/30',
    bg: 'bg-amber-400/10',
    severity: 'high',
    compatibleTargets: ['web-server', 'db-server'],
    description: 'Injects malicious SQL payloads into input fields to extract or corrupt database records.',
    phases: [
      { label: 'Reconnaissance',  duration: 800  },
      { label: 'Payload Crafting', duration: 1000 },
      { label: 'Injection',       duration: 1200 },
      { label: 'Data Exfiltration', duration: 900 },
    ],
    logTemplates: [
      { type: 'attacker', messages: ["sqlmap -u 'http://{ip}/login' --dbs", "Testing payloads: ' OR '1'='1", "UNION SELECT NULL,NULL,NULL--", "Payload: ' OR 1=1;DROP TABLE users--"] },
      { type: 'ids',      messages: ["ALERT: SQL injection attempt on /login", "Signature match: UNION SELECT pattern", "Blocked: ' OR 1=1 payload from {attacker_ip}"] },
      { type: 'firewall', messages: ["WAF rule 8001 triggered: SQL keyword in body", "Rate limit applied to {attacker_ip}", "Connection to DB port 3306 blocked"] },
      { type: 'siem',     messages: ["[HIGH] SQLi campaign detected — 47 blocked payloads", "Correlating with prior recon from {attacker_ip}", "Alert escalated to Tier 2 analyst"] },
    ],
    alertLevel: 'high',
  },
  {
    id: 'ddos',
    name: 'DDoS Flood',
    icon: '🌊',
    category: 'DDoS',
    color: 'text-destructive',
    border: 'border-destructive/30',
    bg: 'bg-destructive/10',
    severity: 'critical',
    compatibleTargets: ['web-server', 'windows-workstation', 'iot-device'],
    description: 'Floods the target with massive packet volumes to exhaust bandwidth and crash services.',
    phases: [
      { label: 'Botnet Assembly',  duration: 700  },
      { label: 'SYN Flood',        duration: 1400 },
      { label: 'UDP Amplification',duration: 1100 },
      { label: 'Service Degradation', duration: 800 },
    ],
    logTemplates: [
      { type: 'attacker', messages: ["Initiating SYN flood — 50,000 pkt/s", "UDP amplification via DNS reflectors", "Botnet activated: 1,200 nodes online", "Sending ICMP flood to {ip}"] },
      { type: 'firewall', messages: ["BLOCKED: SYN flood from 1,200 sources", "Rate limiting: 50k → 200 pkt/s", "Black-hole routing activated for {attacker_ip}", "Upstream ISP null-route request sent"] },
      { type: 'ids',      messages: ["CRITICAL: DDoS signature — pps threshold exceeded", "Geo-block applied: AS{asn}", "Anomaly: 98% traffic from spoofed IPs"] },
      { type: 'siem',     messages: ["[CRITICAL] DDoS attack in progress — bandwidth 9.8 Gbps", "CDN scrubbing centre activated", "NOC on-call notified — SLA at risk"] },
    ],
    alertLevel: 'critical',
  },
  {
    id: 'brute-force',
    name: 'Brute Force',
    icon: '🔨',
    category: 'Credential',
    color: 'text-purple-400',
    border: 'border-purple-400/30',
    bg: 'bg-purple-400/10',
    severity: 'high',
    compatibleTargets: ['web-server', 'windows-workstation', 'db-server'],
    description: 'Systematically tries thousands of credentials to gain unauthorised access to SSH or RDP.',
    phases: [
      { label: 'Wordlist Loading',  duration: 600  },
      { label: 'Auth Hammering',    duration: 1500 },
      { label: 'Account Lockout',   duration: 700  },
      { label: 'Credential Dump',   duration: 900  },
    ],
    logTemplates: [
      { type: 'attacker', messages: ["hydra -l root -P rockyou.txt {ip} ssh", "Trying admin:password123 — FAIL", "Trying root:toor — FAIL", "Trying admin:admin — SUCCESS on attempt 3,847"] },
      { type: 'ids',      messages: ["ALERT: 3,847 failed SSH logins in 60s", "Signature: credential stuffing from {attacker_ip}", "Account 'admin' locked after 10 failures"] },
      { type: 'firewall', messages: ["Blocked: {attacker_ip} — too many auth failures", "Rule added: deny SSH from {attacker_ip}/16", "Port 22 temporarily restricted to allowlist"] },
      { type: 'siem',     messages: ["[HIGH] Brute-force campaign — 4k+ attempts in 2 minutes", "Threat intel match: known botnet IP range", "MFA enforcement triggered for all accounts"] },
    ],
    alertLevel: 'high',
  },
  {
    id: 'ransomware',
    name: 'Ransomware Drop',
    icon: '🔒',
    category: 'Ransomware',
    color: 'text-red-400',
    border: 'border-red-400/30',
    bg: 'bg-red-400/10',
    severity: 'critical',
    compatibleTargets: ['windows-workstation', 'db-server'],
    description: 'Deploys an encrypted payload that locks files and demands a ransom for decryption keys.',
    phases: [
      { label: 'Initial Access',    duration: 900  },
      { label: 'Lateral Movement',  duration: 1100 },
      { label: 'Payload Encryption',duration: 1400 },
      { label: 'Ransom Note Drop',  duration: 600  },
    ],
    logTemplates: [
      { type: 'attacker', messages: ["Executing dropper via phishing macro", "Enumerating SMB shares on {ip}", "Encrypting: C:\\Users\\**\\*.docx ★★★", "Dropping ransom note: README_DECRYPT.txt"] },
      { type: 'ids',      messages: ["CRITICAL: Mass file rename detected (.locked extension)", "Anomaly: SMB traffic spike on {ip}", "Process: cmd.exe spawning vssadmin — BLOCKED"] },
      { type: 'firewall', messages: ["C2 callback to 185.220.101.x BLOCKED", "Egress rule applied — isolating {ip}", "VSS deletion attempt blocked by EDR"] },
      { type: 'siem',     messages: ["[CRITICAL] Ransomware behaviour on {ip}", "Initiating IR playbook: ransomware-001", "Snapshot backup triggered — 3 mins ago"] },
    ],
    alertLevel: 'critical',
  },
  {
    id: 'port-scan',
    name: 'Port Scan',
    icon: '🔍',
    category: 'Recon',
    color: 'text-cyan-400',
    border: 'border-cyan-400/30',
    bg: 'bg-cyan-400/10',
    severity: 'medium',
    compatibleTargets: ['web-server', 'db-server', 'windows-workstation', 'iot-device'],
    description: 'Runs a full Nmap sweep to fingerprint open ports, running services, and OS versions.',
    phases: [
      { label: 'Host Discovery',   duration: 600  },
      { label: 'SYN Scan (-sS)',   duration: 1000 },
      { label: 'Service Probe',    duration: 900  },
      { label: 'OS Fingerprinting',duration: 700  },
    ],
    logTemplates: [
      { type: 'attacker', messages: ["nmap -sS -sV -O {ip}", "Open: 22/tcp ssh OpenSSH 8.9", "Open: 80/tcp http nginx/1.24", "OS guess: Linux 5.x (97% confidence)"] },
      { type: 'ids',      messages: ["NOTICE: Port scan from {attacker_ip}", "SYN packets to 65535 ports in 8s", "Signature: Nmap OS detection probe"] },
      { type: 'firewall', messages: ["Stealth scan detected from {attacker_ip}", "Logging all SYN without ACK", "Source throttled: 10 pkt/s max from {attacker_ip}"] },
      { type: 'siem',     messages: ["[MEDIUM] Recon scan from {attacker_ip}", "Added to watchlist: {attacker_ip}", "Correlating with threat intel feed"] },
    ],
    alertLevel: 'medium',
  },
  {
    id: 'mitm',
    name: 'Man-in-the-Middle',
    icon: '👁',
    category: 'Interception',
    color: 'text-orange-400',
    border: 'border-orange-400/30',
    bg: 'bg-orange-400/10',
    severity: 'critical',
    compatibleTargets: ['web-server', 'windows-workstation', 'iot-device'],
    description: 'Performs ARP poisoning to intercept and inspect traffic between the target and its gateway.',
    phases: [
      { label: 'ARP Poisoning',    duration: 800  },
      { label: 'Traffic Intercept',duration: 1200 },
      { label: 'SSL Stripping',    duration: 1000 },
      { label: 'Data Capture',     duration: 900  },
    ],
    logTemplates: [
      { type: 'attacker', messages: ["arpspoof -i eth0 -t {ip} 10.0.0.1", "SSLstrip listening on :8080", "Captured: POST /login — creds: admin:P@ssw0rd!", "ARP cache poisoned on {ip}"] },
      { type: 'ids',      messages: ["ALERT: Duplicate ARP replies for 10.0.0.1", "MITM signature: ARP poisoning detected", "TLS downgrade attempt on {ip}"] },
      { type: 'firewall', messages: ["Dynamic ARP Inspection triggered", "Rogue ARP entry blocked on VLAN 10", "SSL inspection forced — stripping blocked"] },
      { type: 'siem',     messages: ["[CRITICAL] MITM attack in progress on {ip}", "Credential capture likely — force password reset", "Network isolation recommended for {ip}"] },
    ],
    alertLevel: 'critical',
  },
];

export function getScenarioById(id) {
  return ATTACK_SCENARIOS.find(s => s.id === id) || null;
}